testcontainers.reuse.enable=true

# Connection pool settings
CONNECTION_POOL_MAX_SIZE=10
CONNECTION_MAX_LIFETIME=40000
CONNECTION_TEST_IDLE_INTERVAL_TIME=30000

# JPA settings
PERSISTENCE_NAME=EPOSDataModel

# Cache settings
CACHE_ENABLED=true
CACHE_REFRESH_INTERVAL=600000

# Logging settings
logging.level.org.epos.handler.dbapi=INFO
logging.level.org.eclipse.persistence=INFO